In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/student_performance_modified.csv")
df.head()

,Student_ID,Gender,Study_Hours_per_Week,Attendance_Rate,Past_Exam_Scores,Parental_Education_Level,Internet_Access_at_Home,Extracurricular_Activities,Final_Exam_Score,Pass_Fail
0,S147,Male,31.0,68.267841,86.0,High School,Yes,Yes,63.0,Pass
1,S136,Male,16.0,78.222927,73.0,PhD,No,No,50.0,Fail
2,S209,Female,21.0,87.525096,74.0,PhD,Yes,No,55.0,Fail
3,S458,Female,27.0,92.076483,99.0,Bachelors,No,No,65.0,Pass
4,S078,Female,37.0,98.655517,63.0,Masters,No,Yes,70.0,Pass

In [5]:
df.shape

(1020, 10)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  969 non-null    object
 1   Gender                      969 non-null    object
 2   Study_Hours_per_Week        969 non-null    float64
 3   Attendance_Rate             969 non-null    float64
 4   Past_Exam_Scores            969 non-null    float64
 5   Parental_Education_Level    969 non-null    object
 6   Internet_Access_at_Home     969 non-null    object
 7   Extracurricular_Activities  969 non-null    object
 8   Final_Exam_Score            969 non-null    float64
 9   Pass_Fail                   969 non-null    object
dtypes: float64(4), object(6)
memory usage: 79.8+ KB

In [8]:
df.describe()

,Study_Hours_per_Week,Attendance_Rate,Past_Exam_Scores,Final_Exam_Score
count,969.000000,969.000000,969.000000,969.000000
mean,25.945293,78.161749,77.918742,58.756913
std,8.910053,13.984066,14.542778,6.629587
min,8.532727,48.475715,48.363410,48.843644
25%,19.000000,67.259607,65.000000,52.000000
50%,27.000000,79.648145,79.000000,59.651318
75%,34.000000,89.823589,91.051227,64.000000
max,41.172637,100.644008,100.859127,77.000000

In [9]:
df.isnull().sum()

Student_ID                    51
Gender                        51
Study_Hours_per_Week          51
Attendance_Rate               51
Past_Exam_Scores              51
Parental_Education_Level      51
Internet_Access_at_Home       51
Extracurricular_Activities    51
Final_Exam_Score              51
Pass_Fail                     51
dtype: int64

In [10]:
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

In [11]:

cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipykernel_10209/1920033593.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [12]:
df.isnull().sum()

Student_ID                    0
Gender                        0
Study_Hours_per_Week          0
Attendance_Rate               0
Past_Exam_Scores              0
Parental_Education_Level      0
Internet_Access_at_Home       0
Extracurricular_Activities    0
Final_Exam_Score              0
Pass_Fail                     0
dtype: int64

In [16]:
df.head()

,Student_ID,Gender,Study_Hours_per_Week,Attendance_Rate,Past_Exam_Scores,Parental_Education_Level,Internet_Access_at_Home,Extracurricular_Activities,Final_Exam_Score,Pass_Fail
0,S147,Male,31.0,68.267841,86.0,High School,Yes,Yes,63.0,Pass
1,S136,Male,16.0,78.222927,73.0,PhD,No,No,50.0,Fail
2,S209,Female,21.0,87.525096,74.0,PhD,Yes,No,55.0,Fail
3,S458,Female,27.0,92.076483,99.0,Bachelors,No,No,65.0,Pass
4,S078,Female,37.0,98.655517,63.0,Masters,No,Yes,70.0,Pass

In [22]:
df.groupby('Pass_Fail')['Study_Hours_per_Week'].mean()

Pass_Fail
Fail    23.506031
Pass    28.147910
Name: Study_Hours_per_Week, dtype: float64

In [25]:
df.groupby('Pass_Fail')['Attendance_Rate'].mean()

Pass_Fail
Fail    72.638759
Pass    83.148927
Name: Attendance_Rate, dtype: float64

In [27]:
pd.crosstab(df['Pass_Fail'],df['Gender'])

Gender     Female  Male
Pass_Fail
Fail          243   241
Pass          333   203

In [28]:
pd.crosstab(df['Pass_Fail'],df['Extracurricular_Activities'])

Extracurricular_Activities   No  Yes
Pass_Fail
Fail                        251  233
Pass                        224  312

In [31]:
pd.crosstab(df['Pass_Fail'],df['Parental_Education_Level'])

Parental_Education_Level  Bachelors  High School  Masters  PhD
Pass_Fail
Fail                            112          132      111  129
Pass                            188          109      137  102

In [32]:
pd.crosstab(df['Pass_Fail'],df['Internet_Access_at_Home'])

Internet_Access_at_Home   No  Yes
Pass_Fail
Fail                     242  242
Pass                     334  202

In [36]:
df['Study_Hours_per_Week'].describe()

count    1020.000000
mean       25.945293
std         8.684221
min         8.532727
25%        19.000000
50%        26.000000
75%        34.000000
max        41.172637
Name: Study_Hours_per_Week, dtype: float64

# Insights

1.Study Hours may not impact the more the student either pass or fail,becuase the mean differnce is only 5 hours between pass and fail students.

2.Female students has the high pass oercentage then the male students.

3.student with extracircular activites has high pass percentage then the normal students.

4.students with internet access at home has less pass percentage then the normal students, from the info we consider most of the students missuse the internet .