In [2]:
pip install pandas numpy matplotlib seaborn

Collecting pandasNote: you may need to restart the kernel to use updated packages.

  Using cached pandas-2.3.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy in c:\users\elcot\desktop\ecommerce-recommendation-system\venv\lib\site-packages (2.2.6)
Collecting matplotlib
  Using cached matplotlib-3.10.9-cp310-cp310-win_amd64.whl.metadata (52 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\elcot\desktop\ecommerce-recommendation-system\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\elcot\desktop\ecommerce-recommendation-system\venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\elcot\desktop\ecommerce-recommendation-system\venv\lib\site-packages (from pandas) (2026.2)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.2-cp310-cp310-win_amd64.whl.metadata (5.5 kB)
Requirement already satisfied: cycler>=0.10 in c:\users\elcot\desktop\ecommerce-recommendation-system\venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\elcot\desktop\ecommerce-recommendation-system\venv\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\elcot\desktop\ecommerce-recommendation-system\venv\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\elcot\desktop\ecommerce-recommendation-system\venv\lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\elcot\desktop\ecommerce-recommendation-system\venv\lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\elcot\desktop\ecommerce-recommendation-system\venv\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\users\elcot\desktop\ecommerce-recommendation-system\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
Using cached matplotlib-3.10.9-cp310-cp310-win_amd64.whl (8.2 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached contourpy-1.3.2-cp310-cp310-win_amd64.whl (221 kB)
Installing collected packages: contourpy, pandas, matplotlib, seaborn

   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------------------------------------- 0/4 [contourpy]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]
   ---------- ----------------------------- 1/4 [pandas]

In [2]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [5]:
df = pd.read_csv(r"C:\Users\ELCOT\Desktop\Ecommerce-Recommendation-System\data\raw\ecommerce_data.csv.csv")

In [6]:
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [7]:
df.tail()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,Dec,4,6,1,1,Returning_Visitor,True,False
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,Nov,3,2,1,8,Returning_Visitor,True,False
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,Nov,3,2,1,13,Returning_Visitor,True,False
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,Nov,2,2,3,11,Returning_Visitor,False,False
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,Nov,3,2,1,2,New_Visitor,True,False

In [8]:
df.shape

(12330, 18)

In [9]:
df.columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Month',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType',
       'Weekend', 'Revenue'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  object
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), object(2)
memory usage: 1.5+ MB

In [11]:
df.describe()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,OperatingSystems,Browser,Region,TrafficType
count,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000
mean,2.315166,80.818611,0.503569,34.472398,31.731468,1194.746220,0.022191,0.043073,5.889258,0.061427,2.124006,2.357097,3.147364,4.069586
std,3.321784,176.779107,1.270156,140.749294,44.475503,1913.669288,0.048488,0.048597,18.568437,0.198917,0.911325,1.717277,2.401591,4.025169
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,7.000000,184.137500,0.000000,0.014286,0.000000,0.000000,2.000000,2.000000,1.000000,2.000000
50%,1.000000,7.500000,0.000000,0.000000,18.000000,598.936905,0.003112,0.025156,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000
75%,4.000000,93.256250,0.000000,0.000000,38.000000,1464.157214,0.016813,0.050000,0.000000,0.000000,3.000000,2.000000,4.000000,4.000000
max,27.000000,3398.750000,24.000000,2549.375000,705.000000,63973.522230,0.200000,0.200000,361.763742,1.000000,8.000000,13.000000,9.000000,20.000000

In [12]:
df.dtypes

Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                       object
OperatingSystems             int64
Browser                      int64
Region                       int64
TrafficType                  int64
VisitorType                 object
Weekend                       bool
Revenue                       bool
dtype: object

In [13]:
df.isnull().sum()

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(125)

In [15]:
df.sample(10)

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
4831,5,341.400000,0,0.000000,20,645.709524,0.010526,0.015789,0.000000,0.6,May,1,1,1,3,Returning_Visitor,False,False
1130,0,0.000000,0,0.000000,5,381.666667,0.000000,0.020000,0.000000,0.0,Mar,1,1,3,2,Returning_Visitor,False,False
7103,6,202.400000,1,0.000000,22,2006.046667,0.007143,0.032738,8.052232,0.0,Nov,6,5,4,2,Returning_Visitor,False,False
8440,0,0.000000,0,0.000000,9,273.250000,0.066667,0.077778,0.000000,0.0,Dec,3,3,5,1,Returning_Visitor,True,False
8406,10,301.625000,3,9.000000,122,6919.899495,0.004615,0.022008,0.000000,0.0,Dec,2,2,1,2,Returning_Visitor,False,False
4142,0,0.000000,0,0.000000,1,0.000000,0.200000,0.200000,0.000000,0.0,May,2,10,3,1,Returning_Visitor,False,False
5859,0,0.000000,0,0.000000,1,0.000000,0.200000,0.200000,0.000000,0.0,Nov,2,2,3,13,Returning_Visitor,False,False
647,0,0.000000,0,0.000000,45,1594.283333,0.000000,0.015227,45.431671,0.0,Mar,2,2,1,2,Returning_Visitor,True,True
9701,1,8.000000,0,0.000000,27,787.535714,0.000000,0.005143,0.000000,0.0,Nov,3,2,1,20,Returning_Visitor,False,False
1605,14,1130.502941,6,261.633333,26,2559.898333,0.015789,0.017423,20.304389,0.0,Mar,1,2,1,2,Returning_Visitor,False,False

In [16]:
df.sample(10)

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
10001,1,22.000000,3,39.0,80,1903.081639,0.007229,0.032249,0.000000,0.0,Dec,3,2,1,2,Returning_Visitor,False,False
5862,2,95.300000,0,0.0,14,262.587619,0.012500,0.004911,0.000000,0.0,Nov,1,1,4,2,New_Visitor,False,False
7783,0,0.000000,0,0.0,3,294.700000,0.000000,0.000000,30.203577,0.0,Nov,3,6,3,2,Returning_Visitor,True,True
4479,1,63.000000,0,0.0,24,777.000000,0.025000,0.045833,5.244750,0.4,May,2,2,1,13,Returning_Visitor,False,False
7889,3,70.600000,0,0.0,11,93.500000,0.100000,0.107143,0.000000,0.0,Oct,1,1,1,3,Returning_Visitor,False,False
5318,5,71.666667,1,4.0,59,1702.369048,0.000781,0.009867,6.560625,0.0,May,2,2,6,1,Returning_Visitor,False,True
4013,3,72.500000,4,148.0,24,377.500000,0.006667,0.020000,0.000000,0.6,May,1,1,1,3,Returning_Visitor,False,False
4031,3,13.000000,0,0.0,26,2058.500000,0.000000,0.039506,8.887111,1.0,May,2,2,1,3,Returning_Visitor,True,True
10208,17,856.833333,0,0.0,78,4716.572619,0.011494,0.026156,0.000000,0.0,Dec,3,2,1,1,Returning_Visitor,True,False
10602,1,142.500000,1,48.5,9,733.250000,0.000000,0.018182,0.000000,0.0,Dec,1,1,8,2,New_Visitor,True,False

In [17]:
df["Revenue"].value_counts()

Revenue
False    10422
True      1908
Name: count, dtype: int64

In [18]:
df["VisitorType"].value_counts()

VisitorType
Returning_Visitor    10551
New_Visitor           1694
Other                   85
Name: count, dtype: int64

In [19]:
df["Month"].value_counts()

Month
May     3364
Nov     2998
Mar     1907
Dec     1727
Oct      549
Sep      448
Aug      433
Jul      432
June     288
Feb      184
Name: count, dtype: int64

In [20]:
df.head(20)

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False
5,0,0.0,0,0.0,19,154.216667,0.015789,0.024561,0.0,0.0,Feb,2,2,1,3,Returning_Visitor,False,False
6,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.4,Feb,2,4,3,3,Returning_Visitor,False,False
7,1,0.0,0,0.0,0,0.000000,0.200000,0.200000,0.0,0.0,Feb,1,2,1,5,Returning_Visitor,True,False
8,0,0.0,0,0.0,2,37.000000,0.000000,0.100000,0.0,0.8,Feb,2,2,2,3,Returning_Visitor,False,False
9,0,0.0,0,0.0,3,738.000000,0.000000,0.022222,0.0,0.4,Feb,2,4,1,2,Returning_Visitor,False,False
10,0,0.0,0,0.0,3,395.000000,0.000000,0.066667,0.0,0.0,Feb,1,1,3,3,Returning_Visitor,False,False
11,0,0.0,0,0.0,16,407.750000,0.018750,0.025833,0.0,0.4,Feb,1,1,4,3,Returning_Visitor,False,False
12,0,0.0,0,0.0,7,280.500000,0.000000,0.028571,0.0,0.0,Feb,1,1,1,3,Returning_Visitor,False,False
13,0,0.0,0,0.0,6,98.000000,0.000000,0.066667,0.0,0.0,Feb,2,5,1,3,Returning_Visitor,False,False
14,0,0.0,0,0.0,2,68.000000,0.000000,0.100000,0.0,0.0,Feb,3,2,3,3,Returning_Visitor,False,False
15,2,53.0,0,0.0,23,1668.285119,0.008333,0.016313,0.0,0.0,Feb,1,1,9,3,Returning_Visitor,False,False
16,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.0,Feb,1,1,4,3,Returning_Visitor,False,False
17,0,0.0,0,0.0,13,334.966667,0.000000,0.007692,0.0,0.0,Feb,1,1,1,4,Returning_Visitor,True,False
18,0,0.0,0,0.0,2,32.000000,0.000000,0.100000,0.0,0.0,Feb,2,2,1,3,Returning_Visitor,False,False
19,0,0.0,0,0.0,20,2981.166667,0.000000,0.010000,0.0,0.0,Feb,2,4,4,4,Returning_Visitor,False,False

In [21]:
df.to_csv(r"C:\Users\ELCOT\Desktop\Ecommerce-Recommendation-System\data\raw\ecommerce_data.csv.csv", index=False)