In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv(r"C:\Users\ELCOT\Desktop\Ecommerce-Recommendation-System\data\raw\ecommerce_data.csv.csv")

In [3]:
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [4]:
df.shape

(12330, 18)

In [5]:
df.isnull().sum()

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64

In [6]:
df = df.drop_duplicates()

In [7]:
df.shape

(12205, 18)

In [8]:
df["User_ID"] = range(100001,100001+len(df))

In [9]:
df[["User_ID"]].head()

   User_ID
0   100001
1   100002
2   100003
3   100004
4   100005

In [10]:
df["Product_ID"] = np.random.randint(5001,5301,size=len(df))

In [11]:
df[["Product_ID"]].head()

   Product_ID
0        5033
1        5038
2        5266
3        5120
4        5191

In [12]:
category_map = {
1:"Electronics",
2:"Fashion",
3:"Home",
4:"Books",
5:"Sports",
6:"Beauty",
7:"Toys",
8:"Grocery"
}

df["Category"] = df["TrafficType"].map(category_map)

In [13]:
df["Category"] = df["Category"].fillna("Others")

In [14]:
df["Category"].value_counts()

Category
Fashion        3911
Electronics    2388
Home           2013
Others         1741
Books          1066
Beauty          443
Grocery         343
Sports          260
Toys             40
Name: count, dtype: int64

In [15]:
df["Browsing_Time"] = (
df["Administrative_Duration"] +
df["Informational_Duration"] +
df["ProductRelated_Duration"]
)

In [16]:
df["Browsing_Time"].head()

0      0.000000
1     64.000000
2      0.000000
3      2.666667
4    627.500000
Name: Browsing_Time, dtype: float64

In [17]:
df["Previous_Purchases"] = (
df["ProductRelated"]/5
).astype(int)

In [18]:
np.random.seed(42)

df["Price"] = np.random.randint(500,5000,len(df))

In [19]:
df["Price"].head()

0    1360
1    4272
2    3592
3     966
4    4926
Name: Price, dtype: int32

In [20]:
df["Rating"] = np.where(
df["PageValues"]>20,
5,
np.where(
df["PageValues"]>10,
4,
np.where(
df["PageValues"]>5,
3,
2
)
)
)

In [21]:
df["Rating"].value_counts()

Rating
2    9933
5    1170
4     632
3     470
Name: count, dtype: int64

In [22]:
df["Cart_Addition"] = np.where(
df["PageValues"]>0,
1,
0
)

In [23]:
df["Purchase_Status"] = df["Revenue"].astype(int)

In [24]:
df["Purchase_Status"].value_counts()

Purchase_Status
0    10297
1     1908
Name: count, dtype: int64

In [25]:
np.random.seed(42)

df["Age"] = np.random.randint(
18,
60,
len(df)
)

In [26]:
np.random.seed(42)

df["Gender"] = np.random.choice(
["Male","Female"],
len(df)
)

In [27]:
location_map = {
1:"North",
2:"South",
3:"East",
4:"West",
5:"Central",
6:"North-East",
7:"International",
8:"Urban",
9:"Rural"
}

df["Location"] = df["Region"].map(location_map)

df["Location"] = df["Location"].fillna("Unknown")

In [28]:
df["Discount_Applied"] = np.where(
df["SpecialDay"]>0,
1,
0
)

In [29]:
df["Total_Spending"] = (
df["Price"]*
df["Purchase_Status"]
)

In [30]:
final_df = df[[
"User_ID",
"Product_ID",
"Category",
"Price",
"Rating",
"Browsing_Time",
"Previous_Purchases",
"Cart_Addition",
"Purchase_Status",
"Age",
"Gender",
"Location",
"Discount_Applied",
"Total_Spending"
]]

In [31]:
final_df.head()

,User_ID,Product_ID,Category,Price,Rating,Browsing_Time,Previous_Purchases,Cart_Addition,Purchase_Status,Age,Gender,Location,Discount_Applied,Total_Spending
0,100001,5033,Electronics,1360,2,0.000000,0,0,0,56,Male,North,0,0
1,100002,5038,Fashion,4272,2,64.000000,0,0,0,46,Female,North,0,0
2,100003,5266,Home,3592,2,0.000000,0,0,0,32,Male,Rural,0,0
3,100004,5120,Books,966,2,2.666667,0,0,0,25,Male,South,0,0
4,100005,5191,Books,4926,2,627.500000,2,0,0,38,Male,North,0,0

In [32]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12205 entries, 0 to 12329
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   User_ID             12205 non-null  int64
 1   Product_ID          12205 non-null  int32
 2   Category            12205 non-null  object
 3   Price               12205 non-null  int32
 4   Rating              12205 non-null  int64
 5   Browsing_Time       12205 non-null  float64
 6   Previous_Purchases  12205 non-null  int64
 7   Cart_Addition       12205 non-null  int64
 8   Purchase_Status     12205 non-null  int64
 9   Age                 12205 non-null  int32
 10  Gender              12205 non-null  object
 11  Location            12205 non-null  object
 12  Discount_Applied    12205 non-null  int64
 13  Total_Spending      12205 non-null  int64
dtypes: float64(1), int32(3), int64(7), object(3)
memory usage: 1.3+ MB

In [33]:
final_df.to_csv(
"../data/processed/ecommerce_processed.csv",
index=False
)

In [34]:
check_df = pd.read_csv(
"../data/processed/ecommerce_processed.csv"
)

check_df.head()

,User_ID,Product_ID,Category,Price,Rating,Browsing_Time,Previous_Purchases,Cart_Addition,Purchase_Status,Age,Gender,Location,Discount_Applied,Total_Spending
0,100001,5033,Electronics,1360,2,0.000000,0,0,0,56,Male,North,0,0
1,100002,5038,Fashion,4272,2,64.000000,0,0,0,46,Female,North,0,0
2,100003,5266,Home,3592,2,0.000000,0,0,0,32,Male,Rural,0,0
3,100004,5120,Books,966,2,2.666667,0,0,0,25,Male,South,0,0
4,100005,5191,Books,4926,2,627.500000,2,0,0,38,Male,North,0,0