In [2]:
pip install scikit-learn joblib

Collecting scikit-learn
  Using cached scikit_learn-1.7.2-cp310-cp310-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: joblib in c:\users\elcot\desktop\ecommerce-recommendation-system\venv\lib\site-packages (1.5.3)
Requirement already satisfied: numpy>=1.22.0 in c:\users\elcot\desktop\ecommerce-recommendation-system\venv\lib\site-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: scipy>=1.8.0 in c:\users\elcot\desktop\ecommerce-recommendation-system\venv\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\elcot\desktop\ecommerce-recommendation-system\venv\lib\site-packages (from scikit-learn) (3.6.0)
Using cached scikit_learn-1.7.2-cp310-cp310-win_amd64.whl (8.9 MB)
Installing collected packages: scikit-learn
Successfully installed scikit-learn-1.7.2
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split

import joblib

import warnings
warnings.filterwarnings("ignore")

In [4]:
df = pd.read_csv("../data/processed/ecommerce_processed.csv")

In [5]:
df.head()

,User_ID,Product_ID,Category,Price,Rating,Browsing_Time,Previous_Purchases,Cart_Addition,Purchase_Status,Age,Gender,Location,Discount_Applied,Total_Spending
0,100001,5033,Electronics,1360,2,0.000000,0,0,0,56,Male,North,0,0
1,100002,5038,Fashion,4272,2,64.000000,0,0,0,46,Female,North,0,0
2,100003,5266,Home,3592,2,0.000000,0,0,0,32,Male,Rural,0,0
3,100004,5120,Books,966,2,2.666667,0,0,0,25,Male,South,0,0
4,100005,5191,Books,4926,2,627.500000,2,0,0,38,Male,North,0,0

In [6]:
print(df.shape)

df.info()

(12205, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12205 entries, 0 to 12204
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   User_ID             12205 non-null  int64
 1   Product_ID          12205 non-null  int64
 2   Category            12205 non-null  object
 3   Price               12205 non-null  int64
 4   Rating              12205 non-null  int64
 5   Browsing_Time       12205 non-null  float64
 6   Previous_Purchases  12205 non-null  int64
 7   Cart_Addition       12205 non-null  int64
 8   Purchase_Status     12205 non-null  int64
 9   Age                 12205 non-null  int64
 10  Gender              12205 non-null  object
 11  Location            12205 non-null  object
 12  Discount_Applied    12205 non-null  int64
 13  Total_Spending      12205 non-null  int64
dtypes: float64(1), int64(10), object(3)
memory usage: 1.3+ MB

In [6]:
df.isnull().sum()

User_ID               0
Product_ID            0
Category              0
Price                 0
Rating                0
Browsing_Time         0
Previous_Purchases    0
Cart_Addition         0
Purchase_Status       0
Age                   0
Gender                0
Location              0
Discount_Applied      0
Total_Spending        0
dtype: int64

In [7]:
data = df.copy()

In [8]:
gender_encoder = LabelEncoder()

data["Gender"] = gender_encoder.fit_transform(data["Gender"])

In [9]:
category_encoder = LabelEncoder()

data["Category"] = category_encoder.fit_transform(data["Category"])

In [10]:
data["Category"].head()

0    2
1    3
2    5
3    1
4    1
Name: Category, dtype: int64

In [11]:
location_encoder = LabelEncoder()

data["Location"] = location_encoder.fit_transform(data["Location"])

In [12]:
data.head()

,User_ID,Product_ID,Category,Price,Rating,Browsing_Time,Previous_Purchases,Cart_Addition,Purchase_Status,Age,Gender,Location,Discount_Applied,Total_Spending
0,100001,5033,2,1360,2,0.000000,0,0,0,56,1,3,0,0
1,100002,5038,3,4272,2,64.000000,0,0,0,46,0,3,0,0
2,100003,5266,5,3592,2,0.000000,0,0,0,32,1,5,0,0
3,100004,5120,1,966,2,2.666667,0,0,0,25,1,6,0,0
4,100005,5191,1,4926,2,627.500000,2,0,0,38,1,3,0,0

In [13]:
joblib.dump(
    gender_encoder,
    "../models/gender_encoder.pkl"
)

joblib.dump(
    category_encoder,
    "../models/category_encoder.pkl"
)

joblib.dump(
    location_encoder,
    "../models/location_encoder.pkl"
)

['../models/location_encoder.pkl']

In [14]:
X_reg = data[
[
"Price",
"Browsing_Time",
"Previous_Purchases",
"Discount_Applied",
"Age",
"Category",
"Total_Spending"
]
]

y_reg = data["Rating"]

In [15]:
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(

X_reg,

y_reg,

test_size=0.2,

random_state=42
)

In [16]:
scaler_reg = StandardScaler()

In [17]:
X_train_reg = scaler_reg.fit_transform(
X_train_reg
)

In [18]:
X_test_reg = scaler_reg.transform(
X_test_reg
)

In [19]:
joblib.dump(
scaler_reg,
"../models/regression_scaler.pkl"
)

['../models/regression_scaler.pkl']

In [20]:
X_cls = data[
[
"Browsing_Time",
"Cart_Addition",
"Previous_Purchases",
"Rating",
"Price",
"Discount_Applied",
"Total_Spending"
]
]

y_cls = data["Purchase_Status"]

In [21]:
X_train_cls, X_test_cls, y_train_cls, y_test_cls = train_test_split(

X_cls,

y_cls,

test_size=0.2,

random_state=42
)

In [23]:
scaler_cls = StandardScaler()

X_train_cls = scaler_cls.fit_transform(
X_train_cls
)

X_test_cls = scaler_cls.transform(
X_test_cls
)

In [24]:
joblib.dump(
scaler_cls,
"../models/classification_scaler.pkl"
)

['../models/classification_scaler.pkl']

In [25]:
cluster_data = data[
[
"Browsing_Time",
"Previous_Purchases",
"Total_Spending",
"Rating",
"Price"
]
]

In [26]:
scaler_cluster = StandardScaler()

cluster_scaled = scaler_cluster.fit_transform(
cluster_data
)

In [27]:
joblib.dump(
scaler_cluster,
"../models/clustering_scaler.pkl"
)

['../models/clustering_scaler.pkl']

In [28]:
print("Regression")

print(X_train_reg.shape)

print(X_test_reg.shape)

print()

print("Classification")

print(X_train_cls.shape)

print(X_test_cls.shape)

print()

print("Clustering")

print(cluster_scaled.shape)

Regression
(9764, 7)
(2441, 7)

Classification
(9764, 7)
(2441, 7)

Clustering
(12205, 5)

In [29]:
data.to_csv(

"../data/processed/ecommerce_encoded.csv",

index=False

)